// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team4203.robot;

public interface RobotMap {

	//Motor port mapping
	public static int driveTrainLMotor1 = 0;
    public static int driveTrainLMotor2 = 1;
    public static int driveTrainRMotor1 = 2;
    public static int driveTrainRMotor2 = 3;
    public static int intakeIntakeMotor = 4;
    public static int shooterWinchMotor = 5;
    public static int aimerAimerMotor = 6;
    
    //Solenoid port mapping
    public static int intakePiston1 =0;
    public static int intakePiston2 =1;
    public static int shooterClaw1 = 2;
    public static int shooterClaw2 = 3;

    //Compressor port
    public static int pneumaticsCompressor = 0;


}
